macro(singularityeos_enable_eigen3 target)
  if(NOT TARGET Eigen3::Eigen)
    find_package(Eigen3 REQUIRED)
  endif()
  target_link_libraries(${target} PUBLIC Eigen3::Eigen)
  set(SINGULARITY_EOS_ENABLE_MPARK-VARIANT ON)
endmacro()
