option(SINGULARITY_USE_EIGEN "Use Eigen linear algebra" OFF)

if(SINGULARITY_USE_EIGEN)
    if(SINGULARITY_USE_KOKKOSKERNELS)
        message(FATAL_ERROR "Cannot use Eigen and Kokkoskernels together")
    endif()
    find_package(Eigen3 REQUIRED)
    if(NOT Eigen3_FOUND)
        set(EIGEN_TEST_CXX11 OFF CACHE BOOL "" FORCE)
        set(EIGEN_BUILD_PKGCONFIG OFF CACHE BOOL "" FORCE)
        set(EIGEN_BUILD_DOC OFF CACHE BOOL "" FORCE)
        set(EIGEN_BUILD_TESTING OFF CACHE BOOL "" FORCE)
        add_subdirectory(${PROJECT_SOURCE_DIR}/utils/eigen)
    endif()
    list(APPEND TPL_LIBRARIES Eigen3::Eigen)
    mark_as_advanced(SINGULARITY_USE_EIGEN)
endif()