option(SINGULARITY_USE_EOSPAC "Enable EOSPAC" OFF)
option(SINGULARITY_INVERT_AT_SETUP "Invert start" OFF)
option(SINGULARITY_EOS_SKIP_EXTRAP "Skip extrap" OFF)
mark_as_advanced(SINGULARITY_USE_EOSPAC SINGULARITY_INVERT_AT_SETUP SINGULARITY_EOS_SKIP_EXTRAP)

if(SINGULARITY_USE_EOSPAC)
    find_package(EOSPAC REQUIRED)
    list(APPEND TPL_LIBRARIES EOSPAC::eospac)
    list(APPEND TPL_DEFINES
        SINGULARITY_USE_EOSPAC
        EOSPAC_WARN
    )
    if(SINGULARITY_INVERT_AT_SETUP)
        list(APPEND TPL_DEFINES SINGULARITY_INVERT_AT_SETUP)
    endif()
    if(SINGULARITY_EOS_SKIP_EXTRAP)
        list(APPEND TPL_DEFINES SINGULARITY_EOS_SKIP_EXTRAP)
    endif()
endif()