
 # install
 install(TARGETS ${PROJECT_NAME}
    EXPORT ${PROJECT_NAME}_Targets
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)

include(CMakePackageConfigHelpers)
write_basic_package_version_file("${PROJECT_NAME}ConfigVersion.cmake"
                         VERSION ${PROJECT_VERSION}
                         COMPATIBILITY SameMajorVersion
)

#if(NOT INCLUDE_INSTALL_DIR)
#    set(INCLUDE_INSTALL_DIR include/${PROJECT_NAME})
#endif()

configure_package_config_file(
    "${PROJECT_SOURCE_DIR}/cmake/${PROJECT_NAME}Config.cmake.in"
    "${PROJECT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
    INSTALL_DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/cmake
#    PATH_VARS INCLUDE_INSTALL_DIR
)

install(EXPORT ${PROJECT_NAME}_Targets
 FILE ${PROJECT_NAME}Targets.cmake
 NAMESPACE ${PROJECT_NAME}::
 DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/cmake
)

install(FILES "${PROJECT_BINARY_DIR}/${PROJECT_NAME}/Config.cmake"
     "${PROJECT_BINARY_DIR}/${PROJECT_NAME}ConfigVersion.cmake"
 DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/cmake
)

install(DIRECTORY ${PROJECT_SOURCE_DIR}/${PROJECT_NAME}/
 DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${PROJECT_NAME}
)