name: Warnings

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    warnings-gcc:
      name: Ensure no warnings from gcc
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            submodules: recursive
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: install dependencies
          run: |
            sudo apt-get update -y -qq
            sudo apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages -qq build-essential
        - name: build and run tests
          run: |
            mkdir -p bin
            cd bin
            cmake -DCMAKE_BUILD_TYPE=Debug \
                  -DSINGULARITY_STRICT_WARNINGS=ON \
                  -DSINGULARITY_USE_FORTRAN=OFF \
                  -DSINGULARITY_BUILD_FORTRAN_BACKEND=ON \
                  -DSINGULARITY_BUILD_TESTS=ON \
                  -DSINGULARITY_FORCE_SUBMODULE_MODE=ON \
                  -DSINGULARITY_USE_KOKKOS=ON \
                  ..
            make -j4
